//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSorter {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageSorter.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте путь..
        /// </summary>
        internal static string AddButtonClickTextFolderLV {
            get {
                return ResourceManager.GetString("AddButtonClickTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string AddButtonClickTitleFolderLV {
            get {
                return ResourceManager.GetString("AddButtonClickTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите папку с изображениями..
        /// </summary>
        internal static string ChooseFolderMSG {
            get {
                return ResourceManager.GetString("ChooseFolderMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить список от всех элементов?.
        /// </summary>
        internal static string ClearButtonClickTextFolderLV {
            get {
                return ResourceManager.GetString("ClearButtonClickTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистка списка папок.
        /// </summary>
        internal static string ClearButtonClickTitleFolderLV {
            get {
                return ResourceManager.GetString("ClearButtonClickTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите элемент списка..
        /// </summary>
        internal static string DeleteButtonClickTextFolderLV {
            get {
                return ResourceManager.GetString("DeleteButtonClickTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string DeleteButtonClickTitleFolderLV {
            get {
                return ResourceManager.GetString("DeleteButtonClickTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранную папку из списка?.
        /// </summary>
        internal static string DeleteButtonTextFolderLV {
            get {
                return ResourceManager.GetString("DeleteButtonTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление.
        /// </summary>
        internal static string DeleteButtonTitleFolderLV {
            get {
                return ResourceManager.GetString("DeleteButtonTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка. Данной папки нет или картинка была перемещена/удалена..
        /// </summary>
        internal static string DoubleClickOnLVItemTextFolderLV {
            get {
                return ResourceManager.GetString("DoubleClickOnLVItemTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string DoubleClickOnLVItemTitleFolderLV {
            get {
                return ResourceManager.GetString("DoubleClickOnLVItemTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расширение.
        /// </summary>
        internal static string ExtensionPropLV {
            get {
                return ResourceManager.GetString("ExtensionPropLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В папке нет изображений..
        /// </summary>
        internal static string FolderIsEmptyMSG {
            get {
                return ResourceManager.GetString("FolderIsEmptyMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        internal static string HeightPropLV {
            get {
                return ResourceManager.GetString("HeightPropLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарушен формат записи.
        /// </summary>
        internal static string HotkeyErrorText {
            get {
                return ResourceManager.GetString("HotkeyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задайте горячую клавишу. Разрешена латиница и !@#$%^&amp;*()&lt;&gt;,./:;{}[]\\|/. Не больше одного символа.
        /// </summary>
        internal static string HotkeyText {
            get {
                return ResourceManager.GetString("HotkeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkey.
        /// </summary>
        internal static string HotkeyTitle {
            get {
                return ResourceManager.GetString("HotkeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загруженный профиль, заменит собой все папки. Продолжить?.
        /// </summary>
        internal static string LoadProfileButtonClickText {
            get {
                return ResourceManager.GetString("LoadProfileButtonClickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string LoadProfileButtonClickTitle {
            get {
                return ResourceManager.GetString("LoadProfileButtonClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        internal static string NamePropLV {
            get {
                return ResourceManager.GetString("NamePropLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        internal static string PathPropLV {
            get {
                return ResourceManager.GetString("PathPropLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку.
        /// </summary>
        internal static string RightClickOnLVItemTextFolderLV {
            get {
                return ResourceManager.GetString("RightClickOnLVItemTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам нечего сохранять в профиль. Сначала выберите папки..
        /// </summary>
        internal static string SaveProfileButtonClickText {
            get {
                return ResourceManager.GetString("SaveProfileButtonClickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string SaveProfileButtonClickTitle {
            get {
                return ResourceManager.GetString("SaveProfileButtonClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите папку..
        /// </summary>
        internal static string SkipButtonText {
            get {
                return ResourceManager.GetString("SkipButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string SkipButtonTitle {
            get {
                return ResourceManager.GetString("SkipButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестно.
        /// </summary>
        internal static string UnknownNameFolderLV {
            get {
                return ResourceManager.GetString("UnknownNameFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сначала выберите элемент списка..
        /// </summary>
        internal static string UpdateButtonClickTextFolderLV {
            get {
                return ResourceManager.GetString("UpdateButtonClickTextFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string UpdateButtonClickTitleFolderLV {
            get {
                return ResourceManager.GetString("UpdateButtonClickTitleFolderLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер.
        /// </summary>
        internal static string WeightPropLV {
            get {
                return ResourceManager.GetString("WeightPropLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина.
        /// </summary>
        internal static string WidthPropLV {
            get {
                return ResourceManager.GetString("WidthPropLV", resourceCulture);
            }
        }
    }
}
